### ISSUE TITLE
How to create new session with appPackage and appActivity (not using .apk)

### ISSUE THREAD

**Issue by ptthuong** [mobileboxlab/appium-java-repl#4]
I want to create new session with installed app on Android

**Comment by ehabibov** [comment]
I assume that there is no such possibility. Only application path acceptable.

```
public void start(String deviceName, String udid, String app, String server, String timeout)
      throws CommandsException, MalformedURLException {
    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability(PLATFORM_NAME, ANDROID);
    capabilities.setCapability(DEVICE_NAME, deviceName);
    capabilities.setCapability(NEW_COMMAND_TIMEOUT, timeout);
    capabilities.setCapability(UDID, udid);
    capabilities.setCapability(APP, app);
    setDriver(new AndroidDriver<>(new URL(server), capabilities));
    setDeviceID(udid);
    setApp(app);
  }
```

It would be great if `appPackage.appActivity ` variable will be appropriate in `app` in field of method `android.start(//some capabilities)` because every such launch installs that app like a new one when sometimes there is a need to launch REPL without losing application cache and cookies (like login session).

**Comment by dev-mobileboxlab** [comment]
Now you can use the new scripting capabilities through Nashorn, and set custom capabilities.
